### PR TITLE
modified links in 0-study-lenses/README.md

### PR DESCRIPTION
**Pull request by bermarte**
## Description

Modified links in 0-study-lenses/README.md

### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [x] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### CODE REVIEW

**Comment by colevandersWands** [comment]
@bermarte, did an update fix the problem or are the links still broken for you?

**Comment by bermarte** [comment]
> @bermarte, did an update fix the problem or are the links still broken for you?

Same behavior, I'm in MacOS X and have study-lenses@0.0.171.

**Comment by colevandersWands** [comment]
Are the links broken when you have the folder open, or when you've opened specifically the README?

**Comment by bermarte** [comment]
That's how to reproduce the issue, it happens when I reload the page.
https://github.com/DeNepo/welcome-to-js/assets/979362/4e44c8f2-b4a9-438a-a9c6-10f4dd90f5b2

**Pull request closed without merging**
